version: 2.1
jobs:
  test:
    docker:
      - image: node:12.16
    steps:
      - checkout
      - run:
          name: "install"
          command: "npm install"
      - run:
          name: "test"
          command: npm run test:coverage
workflows:
  build-and-test:
    jobs:
      - test
